### ISSUE TITLE
Modifying Account Names/Balances

### ISSUE THREAD

**Issue by carlosbislip** [wesabe/pfc#34] opened 2010-12-01 22:40 UTC
Editing account names change the balance of the account to a positive balance, regardless of the value.

Balances aren't editable, regardless of modification of the account name.

**Comment by eventualbuddha** [comment] 2010-12-02 16:45
Fix that balances could not be edited to be negative. Closed by 4bc7d3503ed134a093f46f11d783d37a2ee8e6a5.

Regression since 91573cc32.

**Closed as completed by eventualbuddha** 2010-12-02 16:45 UTC
